### ISSUE TITLE
Cannot use pre-msa codon tool on FASTA file 

### ISSUE THREAD

**Issue by xbonner13** [veg/hyphy-analyses#3]
I tried to use this codon pre-msa.bf tool to generate the output file however i have received this error and do not know how to fix it.

Error:Duplicate analysis keyword (not case sensitive) in {CLST, Apply clustering methods for phylogeny reconstruction (UPGMA,WPGMA,complete or minimal \
linkage) to nucleotide, protein and codon data, using MLE of pairwise distances with user-selectable models. These methods produce trees with global mo\
lecular clock., ClusterAnalysis.bf}
Duplicate analysis keyword (not case sensitive) in {CLST, Apply clustering methods for phylogeny reconstruction (UPGMA,WPGMA,complete or minimal linkag\
e) to nucleotide, protein and codon data, using MLE of pairwise distances with user-selectable models. These methods produce trees with global molecula\
r clock., ClusterAnalysis.bf}

I've attached the file to be aligned below 
[7115_sequences_unaligned.txt](https://github.com/veg/hyphy-analyses/files/3184090/7115_sequences_unaligned.txt)

**Comment by spond** [comment]
Dear @xbonner13,

Are you running this on our cluster?

Best,
Sergei

**Comment by xbonner13** [comment]
I am not. But should I?

**Comment by spond** [comment]
Yes, this analysis assumes 2.4 or later of hyphy.

**Comment by xbonner13** [comment]
Right but I have been using version 2.4 locally.

**Comment by spond** [comment]
The error is because your local instance of hyphy is loading an old library version. How are you calling HyPhy?

**Comment by xbonner13** [comment]
./HYPHYMP ../hyphy-analyses/codon-msa/pre-msa.bf --input ../../UnalignedSequences/7115_all_seq.fasta

**Comment by xbonner13** [comment]
Oh yea and this is from inside the hyphy-2.4 folder

**Comment by spond** [comment]
Dear @xbonner13,

What does 

```
$git log
```

and 

```
$git remote -v
```

show on your system?

Best,
Sergei
