### ISSUE TITLE
Could not read command file from 'libv3/all-terms.bf' 

### ISSUE THREAD

**Issue by Joeytbl** [veg/hyphy-analyses#43]
I am trying to run the hyphy standalone analysis, but some errors unexpectedly occur, does someone know how to solve it? 
 
the details are like this: 
Error:
Could not read command file from 'libv3/all-terms.bf' (expanded to '/share/liaoyuxi/software/hyphy-analyses-master/FitMG94/libv3/all-terms.bf') in call to LoadFunctionLibrary("libv3/all-terms.bf", /share/liaoyuxi/software/hyphy-analyses-master/FitMG94/)

would be very appreciated

**Comment by Joeytbl** [comment]
already solved

**Comment by jadamowicz** [comment]
Could you please let me know how you solved this?

**Comment by spond** [comment]
Dear @jadamowicz,

Files not being found usually indicates that HyPhy can't locate its script library files. It will look for files in 

0. User-specified location (given via `LIBPATH=/path/to/files` command line argument). By default this is null (not used).
1. The `res` subdirectory in the Current working directory 
2. The installation location (default is `/usr/local/share/hyphy`)

If you have HyPhy installed from source in some non-default directory (e.g. `/opt/hyphy`), and you call it from a different directory (e.g. `/home/sergei/data`), then specify `LIBPATH=` to indicate where to look for "resources" (libarary files).

```
hyphy LIBPATH=/opt/hyphy/res ...
```

Best,
Sergei

**Comment by Joeytbl** [comment]
> Could you please let me know how you solved this?

just like Sergei said, I added a LIBPATH argument to specify the location of the files
