### ISSUE TITLE
profile likelihood?

### ISSUE THREAD

**Issue by jodyhey** [veg/hyphy-analyses#8]
it would be great if the multi-synonymous code generated confidence intervals for rates/ratios
thanks

**Comment by spond** [comment]
Resolved via c7c05eb2a20110a921e0e8556c01ebb8d27f61ec

**Comment by jodyhey** [comment]
Profile likelihood (confidence intervals)  does not seem to be working in MG94.  e.g. --ci Yes does not lead to ci's in the output.

**Comment by spond** [comment]
Dear @jodyhey,

You mean in the `FitMG94.bf` file?

Best,
Sergei

**Comment by jodyhey** [comment]
I think so.   I'm reporting what Shak told me,  that FitMG94.bf was not returning confidence intervals.

**Comment by spond** [comment]
Dear @jodyhey,

That's because that option only applies to the `multi-synonymous` model. I haven't added it to the `FitMG94.bf` model:)

Best,
Sergei

**Comment by jodyhey** [comment]
Guess I misread the update re #8. 
We are using ci’s as crude way is assessing dn/ds >1.

**Comment by spond** [comment]
Dear @jodyhey,

Do you want me to add a proper LRT for this? 

Best,
Sergei

**Comment by jodyhey** [comment]
The MSS model on MG94 simulated data turned up as we hoped,  i.e. the MSS estimated dn/ds values are similar to the omega value put into the simulation.   This supports the idea that MSS dn/ds values can be the basis of an improved tests for selection under a conventional interpretation,  and given the low correlation between MSS estimated dn/ds values and MG94 estimated dn/ds values,  there is probably a pretty good story to tell about how MG94 dn rates are way off.    
fwiw we saw 4 genes with confidence interval lower bound > 1,  in the 7aa MSS model.  In MG94 all of these genes had estimated dn/ds << 1 
So a short answer would be 'yes',  it would be nice to be able to do LLR tests.

**Comment by spond** [comment]
Dear @jodyhey,

Sure, I'll add LLR; do you want them for each ratio, or just dN/dS?

Best,
Sergei

**Comment by jodyhey** [comment]
If if does not add a ton of work, then all would probably be useful.  The way these things usually go is that you add one thing,  which opens some new ways to think about things, and then you want it generalized.
